apiVersion: v2
name: cubestore
description: A Helm chart for Cubestore
type: application
version: 1.0.1
appVersion: "1.1.14"
keywords:
  - cube
  - cubejs
  - cubestore
maintainers:
  - email: lee@stageten.tv
    name: Lee Horrocks
sources:
  - https://github.com/cube-js/cube.js
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/lazarentertainment/charts
